### ISSUE TITLE
error "redirect_mismatch" when clicking "login" in Chapter 3 front end app

### ISSUE THREAD

**Issue by welkie** [fourTheorem/ai-as-a-service#2] opened 2019-08-08 03:49 UTC
I was able to follow along with Chapter 3 to the point where I work with the AWS web console to set up Cognito. The instructions became unclear around the point where you create a user and update the `.env` file.

The book says "To do this, select
the Users and Groups and click on the Create User button." but stops short of explaining what to do to create the user properly. I used my own judgement and created a user with my personal email address, a temporary password, and turned off the SMS related features. Then I had a user.

The next part of the chapter has us fill in the env vars by checking their values in the web console:

```
# environment defintion for Chapter 3
TARGET_REGION=eu-west-1 1
CHAPTER3_BUCKET=<your bucket name>
CHAPTER3_DATA_BUCKET=<Your data bucket name>
CHAPTER3_DOMAIN=<your development domain>
CHAPTER3_COGNITO_BASE_DOMAIN=<your cognito domain>
CHAPTER3_COGNITO_DOMAIN=<your cognito domain>.auth.eu-west-1.amazoncognito.com 2
CHAPTER3_POOL_ARN=<your user pool ARN>
CHAPTER3_POOL_ID=<your user pool ID>
CHAPTER3_POOL_CLIENT_ID=<your app integration client ID>
CHAPTER3_IDPOOL=<your identity pool ID>
```

The web console for `CHAPTER3_IDPOOL` does not look like the book's screenshots. I found that I had to click on my user pool, and find an "edit" button to get to a screen that looked like this. Additionally, my screen had some warnings about roles that I'm not sure are relevant or not:

![image](https://user-images.githubusercontent.com/7719209/62673817-d6ede700-b96d-11e9-8224-15aced3295c5.png)

When I finished filling out the env vars and deployed the new version of the todo-service and front end app, when I click "login" I get the following error:

![image](https://user-images.githubusercontent.com/7719209/62673797-c9386180-b96d-11e9-9cba-90ac280db7dd.png)

I don't think there's anything in the book that helps me learn why this error occurred. Unfortunately, because it's so tutorial oriented without explaining the AWS services we're creating, I don't know enough about the AWS services to debug it.

**Comment by eoinsha** [comment] 2019-08-08 08:57
Hi @welkie. Thanks for submitting this issue. It's really great feedback and helps us to improve the book 👍 

The web console for `CHAPTER3_IDPOOL` should match the snippet shown in Figure 3.17 but, as you say, you must first selected the identity pool and select the "Edit Identity Pool" option. We have amended the manuscript to reflect this so that will be included in a future MEAP version

The way you followed the "Create User" process is perfect. We will amend the chapter 3 manuscript to outline this more clearly. Thank you for this feedback!

Regarding the `redirect_mismatch` error:
Make sure that the Callback URL and Sign out URLs match the the URL of your S3 bucket _and include the path_ to `index.html` as shown in Figure 3.14. Let us know here if this doesn't resolve your issue. If you still have problems, please let us know below!

**Comment by mattwelke** [comment] 2019-08-08 15:49
@eoinsha Thanks for getting back to me.

Concerning `CHAPTER3_IDPOOL`, I was confident once I found the right page of the web console that I copied the right value in. My concern is that maybe I didn't set up the user pool or identity pool correctly.

I think I did use the correct S3 bucket URL for the callback URL and sign out URL. Notice how the URL `https://s3-eu-west-1.amazonaws.com/mattwelke-sandbox-as-a-service-chap3/index.html` brings me to my SPA:

![image](https://user-images.githubusercontent.com/7719209/62717419-dd15af00-b9d1-11e9-917e-f8318650951e.png)

And that I'm using it as for each URL:

![image](https://user-images.githubusercontent.com/7719209/62717464-f4ed3300-b9d1-11e9-9273-59e9aee36f04.png)

I noticed that there are two forms of URL for the S3 bucket that allow the web browser to access it, one with subdomain and one with subdirectory:

- https://s3-eu-west-1.amazonaws.com/mattwelke-sandbox-as-a-service-chap3/index.html
- https://mattwelke-sandbox-as-a-service-chap3.s3-eu-west-1.amazonaws.com/index.html

But I used the style that the book's screenshot uses, which is the subdirectory style.

There are a few differences in my setup compared to the default way one would set their AWS account up for the book, but I don't think they affect this. I had no problems so far:

- I do not use the root account. I set up an IAM user with Administrator role and I sign in to that IAM user to perform the tasks the book needs.
- I use a subdomain (`aaas.mattwelke.com`) instead of dedicating a whole domain to the book, so that I can complete the tasks in the book without purchasing a second domain. I used Route 53 to set up the hosted zone with this subdomain, which gives me four NS record values, which I set in my DNS provider (Cloudflare) for the subdomain, so that my DNS provider delegates DNS duty for the subdomain to Route 53.

If you'd like to see my complete `.env` file to get a sense of whether I grabbed the right values, please send me an email at REDACTED and I can provide them to you.

**Comment by eoinsha** [comment] 2019-08-08 16:08
@welkie, your mention of the two different S3 URL syntaxes might be on to something. I suspect that the client is configured to use the (older) subdomain syntax and this is actually taken directly from the Listing in 3.17 (Amplify configuration). Would you be willing to try editing the front end configuration to use the subdirectory URL syntax, matching what you have set in the Cognito settings?

Many thanks. By the way, your IAM user and subdomain setup are completely fine - both great practices applied correctly.

**Comment by welkie** [comment] 2019-08-08 16:36
Good catch. It was the URL being created by the build process. It needed to be switched to include the target region and use the subdirectory style.

Before:

```js
const oauth = {
  domain: process.env.CHAPTER3_COGNITO_DOMAIN,
  scope: ['email'],
  redirectSignIn: `https://${process.env.CHAPTER3_BUCKET}.s3.amazonaws.com/index.html`,
  redirectSignOut: `https://${process.env.CHAPTER3_BUCKET}.s3.amazonaws.com/index.html`,
  responseType: 'token'
}
```

After:

```js
const oauth = {
  domain: process.env.CHAPTER3_COGNITO_DOMAIN,
  scope: ['email'],
  redirectSignIn: `https://s3-${process.env.TARGET_REGION}.amazonaws.com/${process.env.CHAPTER3_BUCKET}/index.html`,
  redirectSignOut: `https://s3-${process.env.TARGET_REGION}.amazonaws.com/${process.env.CHAPTER3_BUCKET}/index.html`,
  responseType: 'token'
}
```

![image](https://user-images.githubusercontent.com/7719209/62720946-1b629c80-b9d9-11e9-8604-010c69377d7e.png)

Thanks for helping out. :)

**Comment by eoinsha** [comment] 2019-08-09 11:12
Great to see that the issue is solved. Thanks very much for your help in resolving!

**Closed by eoinsha** 2019-08-09 11:12 UTC
